name: update
on:
  schedule:
  - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install jupyter
        pip install babino2020masks
    - name: Update daily
      run: jupyter nbconvert --to notebook --execute --inplace _notebooks/2020-11-16-daily.ipynb
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: automatic daily update
        branch: master
        push_options: '--force'
    - name: convert notebooks and word docs to posts
      uses: fastai/fastpages@master
    - name: Jekyll build
      uses: docker://jekyll/jekyll
      with:
        args: jekyll build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push'
      with:
        deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./_site
